name: 080-resusable-workflow-caller

on:
  push:
    branches: none # [ main ]
  pull_request:
    branches: none # [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  call-workflow-A:
    uses: deepaksharma2007/github-action-examples/.github/workflows/06-reusable-workflow-called.yml@main
    with:
      username: deepak
    secrets:
      token: ${{ secrets.TOKEN }}

  call-workflow-B:
    uses: deepaksharma2007/github-action-examples/.github/workflows/06-reusable-workflow-called.yml@main
    with:
      username: Raj
    secrets:
      token: ${{ secrets.TOKEN }}
